/**
 * ORION Software Activation Page
 * 
 * Displayed when ORION is newly installed on a computer without an active license.
 * Requires an authentic Product Key generated by the Master Admin.
 * Verifies the key 100% offline using cryptographic signatures.
 */

import { useState, useEffect } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import {
  ShieldCheck,
  KeyRound,
  Laptop,
  Copy,
  Check,
  ArrowRight,
  Sparkles,
  Building2,
  Lock,
  HelpCircle,
} from 'lucide-react'
import { Button } from '@components/ui/Button'
import { Input } from '@components/ui/Input'
import { Card } from '@components/ui/Card'
import { Modal } from '@components/ui/Modal'
import { useNotificationStore } from '@store/notification.store'
import { useAuthStore } from '@store/auth.store'
import {
  getDeviceFingerprint,
  activateSoftwareLicense,
  getActiveLicense,
} from '@/services/licensing.service'
import { isSetupComplete } from '@services/business.service'
import { unlockMasterAdminWithPasskey } from '@services/auth.service'

export default function ActivateSoftware() {
  const [deviceFingerprint, setDeviceFingerprint] = useState('')
  const [clientName, setClientName] = useState('')
  const [productKey, setProductKey] = useState('')
  const [copiedDevice, setCopiedDevice] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [isSuccess, setIsSuccess] = useState(false)
  const [searchParams] = useSearchParams()

  // Secret Vendor Unlock
  const [showVendorModal, setShowVendorModal] = useState(false)
  const [vendorPasskey, setVendorPasskey] = useState('')
  const [isUnlockingVendor, setIsUnlockingVendor] = useState(false)
  const [secretClickCount, setSecretClickCount] = useState(0)

  const { setSession } = useAuthStore()
  const { success, error } = useNotificationStore()
  const navigate = useNavigate()

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.ctrlKey || e.metaKey) && e.altKey && e.shiftKey && e.key.toLowerCase() === 'a') {
        e.preventDefault()
        setShowVendorModal(true)
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [])

  async function handleVendorUnlock(e: React.FormEvent) {
    e.preventDefault()
    if (!vendorPasskey.trim()) return

    setIsUnlockingVendor(true)
    try {
      const result = await unlockMasterAdminWithPasskey(vendorPasskey)
      if (!result.success || !result.user) {
        error('Access Denied', result.error || 'Invalid Master Vendor Passkey.')
        return
      }

      setSession(result.user)
      success('Master Access Granted', 'Logged in to Master Admin Portal')
      setShowVendorModal(false)
      navigate('/admin', { replace: true })
    } catch (err: unknown) {
      console.error('[Vendor Unlock] Error:', err)
      const msg = err instanceof Error ? err.message : String(err)
      error('Access Denied', msg)
    } finally {
      setIsUnlockingVendor(false)
    }
  }

  useEffect(() => {
    async function init() {
      const devId = await getDeviceFingerprint()
      setDeviceFingerprint(devId)

      // If already activated, redirect to login or dashboard
      const lic = await getActiveLicense()
      if (lic.isActivated) {
        const setupDone = await isSetupComplete()
        navigate(setupDone ? '/login' : '/setup', { replace: true })
      }
    }
    init()
  }, [navigate])

  function handleCopyDevice() {
    if (!deviceFingerprint) return
    navigator.clipboard.writeText(deviceFingerprint)
    setCopiedDevice(true)
    setTimeout(() => setCopiedDevice(false), 2000)
    success('Device ID Copied', 'Share this Device ID with your software provider.')
  }

  // Format key input automatically (uppercase and grouped)
  function handleKeyChange(val: string) {
    const raw = val.toUpperCase().replace(/[^A-Z0-9-]/g, '')
    setProductKey(raw)
  }

  async function handleActivate(e: React.FormEvent) {
    e.preventDefault()
    if (!clientName.trim()) {
      error('Missing Business Name', 'Please enter your registered Business or Client Name.')
      return
    }
    if (!productKey.trim()) {
      error('Missing Product Key', 'Please enter your genuine Product Key.')
      return
    }

    setIsLoading(true)
    try {
      const res = await activateSoftwareLicense(productKey, clientName)
      if (!res.success || !res.license) {
        error('Activation Failed', res.error || 'Invalid or unverified Product Key.')
        return
      }

      setIsSuccess(true)
      success(
        'ORION Activated Successfully!',
        `License Type: ${res.license.plan?.toUpperCase()} (${res.license.edition?.toUpperCase()} Edition)`,
      )

      setTimeout(() => {
        navigate('/setup', { replace: true })
      }, 1200)
    } catch (err: unknown) {
      console.error('[Activate] Error:', err)
      const msg = err instanceof Error ? err.message : String(err)
      error('Activation Error', msg)
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-[#F0F2F5] flex flex-col justify-center items-center p-4">
      <div className="w-full max-w-lg bg-white rounded-2xl shadow-orion-lg border border-orion-border overflow-hidden">
        {/* Header Banner */}
        <div className="bg-[#18191B] text-white px-8 py-8 flex flex-col items-center text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
            <KeyRound size={120} />
          </div>

          <div className="w-16 h-16 rounded-2xl overflow-hidden mb-3.5 border-2 border-white/20 shadow-lg bg-white flex-shrink-0">
            <img src="/logo.png" alt="ORION" className="w-full h-full object-cover" />
          </div>

          <h1 className="text-xl font-bold tracking-tight text-white">Activate ORION</h1>
          <p className="text-xs text-gray-400 mt-1 max-w-sm">
            Please enter your registered Business Name and genuine Product Key to activate this machine.
          </p>
        </div>

        {/* Content Body */}
        <div className="p-8 space-y-6">
          {/* Machine Fingerprint Card */}
          <div className="p-3.5 rounded-xl bg-gray-50 border border-gray-200/80 flex items-center justify-between gap-3">
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="p-2 rounded-lg bg-white border border-gray-200 text-gray-700 shrink-0">
                <Laptop size={16} />
              </div>
              <div className="min-w-0">
                <p className="text-[11px] font-medium text-gray-500 uppercase tracking-wider">This Machine ID</p>
                <p className="font-mono text-xs font-semibold text-gray-900 truncate">
                  {deviceFingerprint || 'Detecting hardware...'}
                </p>
              </div>
            </div>

            <Button
              type="button"
              variant="secondary"
              size="sm"
              onClick={handleCopyDevice}
              className="text-xs shrink-0 flex items-center gap-1"
            >
              {copiedDevice ? <Check size={13} className="text-green-600" /> : <Copy size={13} />}
              {copiedDevice ? 'Copied' : 'Copy ID'}
            </Button>
          </div>

          {/* Activation Form */}
          <form onSubmit={handleActivate} className="space-y-4">
            <div>
              <Input
                label="Registered Business / Client Name"
                required
                value={clientName}
                onChange={(e) => setClientName(e.target.value)}
                placeholder="e.g. Balaji Garments or Sharma Traders"
                hint="Enter the exact business name provided during license purchase"
                autoFocus
              />
            </div>

            <div>
              <Input
                label="Product Key (License Key)"
                required
                value={productKey}
                onChange={(e) => handleKeyChange(e.target.value)}
                placeholder="ORION-PRO-XXXX-XXXX-XXXX-XXXX"
                hint="Format: ORION-PRO-XXXX-XXXX-XXXX-XXXX (25 characters)"
                className="font-mono tracking-wider"
              />
            </div>

            <Button
              type="submit"
              variant="primary"
              fullWidth
              size="lg"
              isLoading={isLoading}
              disabled={isSuccess}
              rightIcon={<ArrowRight size={16} />}
              className="mt-6 bg-indigo-600 hover:bg-indigo-700"
            >
              {isSuccess ? 'Activated!' : 'Activate Software'}
            </Button>
          </form>

          {/* Notice for Client */}
          <div className="pt-4 border-t border-orion-border text-center text-xs text-gray-500">
            <p>
              Don't have a Product Key yet? Contact your ORION software vendor to purchase and activate your license.
            </p>
          </div>
        </div>
      </div>

      <div
        onClick={() => {
          setSecretClickCount((prev) => {
            if (prev + 1 >= 5) {
              setShowVendorModal(true)
              return 0
            }
            return prev + 1
          })
        }}
        className="mt-6 text-center text-xs text-gray-400 cursor-default select-none transition-colors hover:text-gray-500"
      >
        <p className="font-medium text-gray-500">
          &copy; 2026 ORION INC. All rights reserved.
        </p>
      </div>

      {/* Secret Master Vendor Access Modal */}
      <Modal
        isOpen={showVendorModal}
        onClose={() => {
          if (!isUnlockingVendor) {
            setShowVendorModal(false)
            setVendorPasskey('')
          }
        }}
        title="Master Vendor Security Access"
        size="sm"
      >
        <form onSubmit={handleVendorUnlock} className="space-y-4">
          <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-900 flex items-start gap-2">
            <Lock size={15} className="text-amber-600 shrink-0 mt-0.5" />
            <div>
              <strong>Vendor Authorization Required:</strong> Enter your secret Master Vendor Passkey to access administration.
            </div>
          </div>

          <div>
            <label className="text-xs font-medium text-gray-700 block mb-1">
              Master Vendor Passkey
            </label>
            <input
              type="password"
              required
              autoFocus
              value={vendorPasskey}
              onChange={(e) => setVendorPasskey(e.target.value)}
              placeholder="••••••••••••••••"
              className="w-full px-3 py-2 text-sm font-mono border border-orion-border rounded-lg bg-gray-50 focus:bg-white focus:ring-2 focus:ring-amber-500 outline-none"
            />
          </div>

          <div className="pt-2 flex justify-end gap-2">
            <Button
              type="button"
              variant="ghost"
              onClick={() => {
                setShowVendorModal(false)
                setVendorPasskey('')
              }}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              variant="primary"
              isLoading={isUnlockingVendor}
              className="bg-amber-600 hover:bg-amber-700"
            >
              Unlock Master Admin
            </Button>
          </div>
        </form>
      </Modal>
    </div>
  )
}
